config/routes.rb
Expman::Application.routes.draw do
  devise_for :users

  get 'expenses/statistics'
  get 'expenses/new_income'
  resources :expenses

  get 'categories/customize'
  resources :categories do
      put :score, on: :collection
  end

  resources :locations

  match 'budget_items/create_budget', via: :post
  match 'budget_items/edit_budget', via: :get
  match 'budget_items/update_budget', via: :put
  match 'budget_items/delete_budget', via: :delete
  resources :budget_items
  
  #match 'locations', to: 'locations#index', via: :get

  root to: 'high_voltage/pages#show', id: 'homepage'
  #match '/delete', to: 'expenses#destroy', via: 'delete'

end

app/models/budget_item.rb
class BudgetItem < ActiveRecord::Base
	belongs_to :user
	belongs_to :category

	validates :user_id, presence: true
	validates_uniqueness_of :budget_date, :scope => [:category_id, :user_id]

	validates_numericality_of :value, allow_nil: true
end

app/controllers/budget_items_controller.rb
class BudgetItemsController < ApplicationController

	def index
		@categories = Category.where(active: true).sort{|x,y| counts(y.id) <=> counts(x.id)}
		
		@budget_items = current_user.budget_items.where(budget_date: Date.today.at_beginning_of_month).order('category_id ASC')
		@date1 = Date.today 
		@date2 = @date1.strftime("%B")
		@total = @budget_items.sum(:value)

		@budget_items_next = current_user.budget_items.where(budget_date: (Date.today + 1.month).at_beginning_of_month).order('category_id ASC')
		@date3 = Date.today  + 1.month
		@date4 = @date3.strftime("%B")
		@total_next = @budget_items_next.sum(:value)
		
	end

	def counts(category_id)
		@expenses1 = current_user.expenses
		@categories1 = Category.all
		@categories1.each do |sorted_categories|
			@sorted_categories = @expenses1.where(category_id: category_id).count
		end
		return @sorted_categories
	end

	def new
		@categories = Category.where(active: true).sort{|x,y| counts(y.id) <=> counts(x.id)}
		@categories2 = Category.where(active: true, outcome: true)
	end

	def create_budget
		@categories = Category.where(active: true).sort{|x,y| counts(y.id) <=> counts(x.id)}
		@categories2 = Category.where(active: true, outcome: true)

		#date = params[:budget_items].map {|array2| array2.first}
		@date = params[:budget_date]

		params[:budget_items].each do |p|
       	@budget_items =	current_user.budget_items.create(p.merge(budget_date: @date))
		end
		if @budget_items.save
			redirect_to budget_items_path
		else
			render 'new'
		end
	end

	def edit_budget
		@budget_items = BudgetItem.find(params[:budget_ids])
	end

	def update_budget
		@budget_items = BudgetItem.update(params[:budget_items].keys, params[:budget_items].values)
		@budget_items.reject!{ |p| p.errors.empty? }

		if @budget_items.empty?
			redirect_to budget_items_path
		else
			render 'edit_budget'
		end
	end

	def edit
		@categories = Category.where(active: true).sort{|x,y| counts(y.id) <=> counts(x.id)}

		@budget_item = BudgetItem.find(params[:id])
	end

	def update
		@categories = Category.where(active: true).sort{|x,y| counts(y.id) <=> counts(x.id)}
		@categories2 = Category.where(active: true, outcome: true)
		
		@budget_item = current_user.budget_items.find(params[:id])
		@budget_item.update(budget_params)

		if @budget_item.save
			redirect_to budget_items_path
		else
			render 'edit'
		end
	end

	def destroy
		@budget_item = current_user.budget_items.find(params[:id])
		@budget_item.destroy
   	redirect_to budget_items_path
	end

	def delete_budget
		@budget_items = current_user.budget_items.where(budget_date: Date.today.at_beginning_of_month)
		@budget_items.each do |budget_item|
			budget_item.destroy
		end
		redirect_to budget_items_path
	end

	private
	
	def budget_params
		params.require(:budget_item).permit(:value, :budget_date, :category_id, :user_id)	
	end
end

app/views/budget_items/_budgets.html.erb
<ul class="nav nav-tabs">
	<li class="active"> <%= link_to "Show", budget_items_path %></li>
	<li ><%= link_to "New", new_budget_item_path %></li>
	<li><%= link_to "Delete", budget_items_delete_budget_path(@budget_items), method: :delete, data: {confirm: 'Are you sure?'} %></li>
	<div class="panel panel-default">
		<div align="right" class="panel-heading">Expense Manager</div>
			<div class="panel-body">
				<div class="well" align="center" style="font-size:35px"><span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;Monthly Budget</div>
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>Budget for <%= @date2 %></strong>
					</div>
					<%= form_tag budget_items_edit_budget_path, method: :get do %>
						<table class="table">
						<tr>
							<th></th>
							<th>Category</th>
							<th>Budget</th>
							<th></th>
							<th></th>
						</tr>
						<% @budget_items.each do |budget| %>
							<tr>
								<td><%= check_box_tag "budget_ids[]", budget.id %> </td>
								<td><%= budget.category.name %></td>
								<td><%= number_with_precision(budget.value, :precision => 2, :delimiter => ',') %> €</td>
								<td><%= link_to "Edit", edit_budget_item_path(budget), class: "btn btn-primary" %></td>
								<td><%= link_to "Delete", budget_item_path(budget), class: "btn btn-default", method: :delete, data: {confirm: 'Are you sure?', role: "button"} %></td>
							</tr>
						<% end %>
						<tr>
							<th></th>
							<th>Total</th>
							<th><%= number_with_precision(@total, :precision => 2, :delimiter => ',') %> €</th>
							<th></th>
							<th></th>
						</table>
				</div>
				<%= submit_tag "Edit checked", class: "btn btn-default", id: "current-month" %><br/></br>
				<% end %>
						Click bellow on Show to see your budget for the next month.<br/>
						<a id="show_id" onclick="document.getElementById('spoiler_id').style.display=''; document.getElementById('show_id').style.display='none';" class="link">[Show]</a><span id="spoiler_id" style="display: none"><a onclick="document.getElementById('spoiler_id').style.display='none'; document.getElementById('show_id').style.display='';" class="link">[Hide]</a>
						<div class="panel panel-default">
							<div class="panel-heading">
							<strong>Budget for <%= @date4 %></strong>
							</div>
							<%= form_tag budget_items_edit_budget_path, method: :get do %>
							<table class="table">
							<tr>
								<th>Category</th>
								<th>Budget</th>
								<th></th>
								<th></th>
							</tr>
							<% @budget_items_next.each do |budget| %>
								<tr>
									<td><%= check_box_tag "budget_ids[]", budget.id %> </td>
									<td><%= budget.category.name %></td>
									<td><%= number_with_precision(budget.value, :precision => 2, :delimiter => ',') %> €</td>
									<td><%= link_to "Edit", edit_budget_item_path(budget), class: "btn btn-primary" %></td>
									<td><%= link_to "Delete", budget_item_path(budget), class: "btn btn-default", method: :delete, data: {confirm: 'Are you sure?', role: "button"} %></td>
								</tr>
							<% end %>
							<tr>
								<th></th>
								<th>Total</th>
								<th><%= number_with_precision(@total_next, :precision => 2, :delimiter => ',') %> €</th>
								<th></th>
								<th></th>
							</table>
						</div>
						<%= submit_tag "Edit checked", class: "btn btn-default", id: "next-month" %><br/></br>
						<% end %>
						</span>

				</div>
			</div>
		</div>
	</div>
</ul>

app/views/budget_items/_create_budget.html.erb
<ul class="nav nav-tabs">
  <li > <%= link_to "Show", budget_items_path %></li>
  <li class="active"><%= link_to "New", new_budget_item_path %></li>
  <li><%= link_to "Delete" %></li>
  <div class="panel panel-default">
    <div align="right" class="panel-heading">Expense Manager</div>
      <div class="panel-body">
        <div class="well" align="center" style="font-size:35px"><span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;Monthly Budget</div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong>Add your monthly budget</strong>
          </div>
          
          <div class="panel-body">
          <p>Enter the amount of money you want to spend by your <%= link_to "active categories", categories_customize_path %>. If you don't want to spend money in some category, leave the field blank.<br/>
          <strong>Note:</strong> On the first in 10:00 AM of every month, the budget of the previous month will be coppied to the next if you didn't defined your own.</p>
          <%= form_tag budget_items_create_budget_path, method: :post do %>
            <div class="date" data-behaviour="datepicker1">
              <%= label_tag "Month" %>
              <%= text_field_tag 'budget_date', Date.today.at_beginning_of_month, class: "form-control"%><p class="input-group-addon"></p>
            </div>
            <% @categories2.each do | cat | %>
              <%= label_tag cat.id, cat.name %> 
              <%= text_field_tag 'budget_items[][value]', nil, class: 'form-control', id: "#{cat.id}" %>
              <%= hidden_field_tag 'budget_items[][category_id]', cat.id %>
            <% end %><br/>
            <%= submit_tag("Submit", class: "btn btn-primary") %>
          <% end %>
        </div> 

        </div>
      </div>
    </div>
  </div>
</ul>

app/views/budget_items/_update_budgets.html.erb
<% if @budget_item.errors.any? %>
   <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <ul>
         <% @budget_item.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
         <% end %>
      </ul>
   </div>
<% end %>
<ul class="nav nav-tabs">
  <li class="active"> <%= link_to "Show", budget_items_path %></li>
  <li ><%= link_to "Edit" %></li>
  <li><%= link_to "Delete" %></li>
  <div class="panel panel-default">
    <div align="right" class="panel-heading">Monthly Budget</div>
      <div class="panel-body">
        <div class="well" align="center" style="font-size:35px"><span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;Monthly Budget</div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong>Category budget</strong>
          </div>
          <div class="panel-body">
            <table class="table">
            <%= form_for @budget_item, {role: "form"} do |f| %> 
              <legend>Edit budget item</legend>     
              <div class="form-group">
                <%= f.label :value, "Category budget" %>
                <%= f.text_field :value, class: "form-control" %>
                <div class="date" data-behaviour="datepicker">
                <%= f.label :budget_date, "Date" %>
                <%= f.text_field :budget_date, value: Date.today.at_beginning_of_month, class: "form-control"%><p class="input-group-addon"></p>
                </div>
              </div>
              <button type="submit" method="patch" class="btn btn-primary">Save changes</button>
            <% end %>
            </table>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</ul>

app/views/budget_items/edit.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Expense manager</title>
  </head>
  <body>

  <div class="container">
    <div class="row">
    <%= render 'expenses/categories_list' %>
    <div class="col-md-2">
    </div>
    <div class="col-md-5">
    <br/>
        <div class="row">
              <br/><div class="thumbnail">
          <%= render 'update_budgets' %>
        </div>
      </div>
    </div>
    <div class="col-md-2">
    </div>
    </div>
  </div>
  </body>
</html>

app/views/budget_items/edit_budget.html.erb
<div class="col-md-5 center-block">
	<div class="panel panel-default">
	  <div class="panel-heading">Monthly budget management</div>
	  <div class="panel-body">
	    <p>Edit the budgets for the selected categories. If you want to set a budget to 0, we recommand you to use the delete button on the show page.</p>	
		<%= form_tag budget_items_update_budget_path, method: :put do %>
			<% @budget_items.each do |budget_item| %><br/>
				<strong><%= budget_item.category.name %></strong>
				<%= fields_for "budget_items[]", budget_item do |f| %>
				  <% if budget_item.errors.any? %>
				   <div class="alert alert-error">
				      <button type="button" class="close" data-dismiss="alert">&times;</button>
				      <ul>
				         <% budget_item.errors.full_messages.each do |msg| %>
				         <li><%= msg %></li>
				         <% end %>
				      </ul>
				   </div>
					<% end %>
					<%= f.text_field :value, class: "form-control" %>
					<%= f.label :category_id, "Change category" %>
          			<%= f.collection_select(:category_id, Category.where(active: true, outcome: true), :id, :name,  {prompt: "Select a category"}, {class: "form-control"}) %>
				<% end %><br/>
			<% end %><br/>
			<%= submit_tag "Update", class: "btn btn-default" %>
		<% end %>
	  </div>
	</div>
</div>

app/views/budget_items/index.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Expense manager</title>
  </head>
  <body>

  <div class="container">
    <div class="row">
    <%= render 'expenses/categories_list' %>
    <div class="col-md-2">
    </div>
    <div class="col-md-5">
        <div class="row">
              <br/><div class="thumbnail">
          <%= render 'budgets' %>
        </div>
      </div>
    </div>
    <div class="col-md-2">
    </div>
    </div>
  </div>
  </body>
</html>

app/views/budget_items/new.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Expense manager</title>
  </head>
  <body>

  <div class="container">
    <div class="row">
      <%= render 'expenses/categories_list' %>
      <div class="col-md-2">
      </div>
      <div class="col-md-5">
        <div class="row">
          <br/>
          <div class="thumbnail">
            <%= render 'create_budget' %>
          </div>
        </div>
      </div>
      <div class="col-md-2">
      </div>
    </div>
  </div>
  </body>
</html>