config/routes.rb
Expman::Application.routes.draw do
  devise_for :users

  get 'expenses/statistics'
  get 'expenses/new_income'
  resources :expenses

  get 'categories/customize'
  resources :categories do
      put :score, on: :collection
  end

  resources :locations

  match 'budget_items/create_budget', via: :post
  match 'budget_items/edit_budget', via: :get
  match 'budget_items/update_budget', via: :put
  match 'budget_items/delete_budget', via: :delete
  resources :budget_items
  
  #match 'locations', to: 'locations#index', via: :get

  root to: 'high_voltage/pages#show', id: 'homepage'
  #match '/delete', to: 'expenses#destroy', via: 'delete'

end

app/controllers/expenses_controller.rb
#require 'will_paginate/array' 
require 'csv'

class ExpensesController < ApplicationController

	def counts(category_id)
		@expenses1 = current_user.expenses
		@categories1 = Category.all
		@categories1.each do |sorted_categories|
			@sorted_categories = @expenses1.where(category_id: category_id).count
		end
		return @sorted_categories
	end

	def index

		@categories = Category.where('active = true').sort{|x,y| counts(y.id) <=> counts(x.id)}

		if params[:category] && params[:search]
			@expenses = search_description
			@expenses.select!{ |c| c.category_id == params[:category] }.order('date DESC')
		elsif params[:category]
			@expenses = current_user.expenses.where(category_id: params[:category]).order('date DESC')
		elsif params[:search]
			@expenses = search_description.records
		else
			@expenses = current_user.expenses.order('date DESC')
		end
			#@expenses = @expenses.order('date DESC').page(params[:page]).per_page(8)

		@income = current_user.expenses.where("date > ? and outcome = false", Date.today.at_beginning_of_month).sum(:expense_value)
		@outcome = current_user.expenses.where("date > ? and outcome = true", Date.today.at_beginning_of_month).sum(:expense_value)
		@total = @income - (@outcome).abs

		@budget_items = current_user.budget_items.where(budget_date: Date.today.at_beginning_of_month)
		@budget = @budget_items.sum(:value)

		@money_left = @budget - (@total).abs

		@percentage = ((@total.abs)/@budget)*100

		respond_to do |format|
			format.html
			format.csv { send_data @expenses.to_csv }
			format.xls #{ send_data @expenses.to_csv(col_sep: "\t") }
		end
	end

	def search_description
		#current_user.expenses.order('date DESC').page(params[:page]).per_page(8).search(params[:search], where: {user_id: current_user.id})
		#current_user.expenses.where(['lower(description) LIKE ?', "%#{params[:search]}%"])
		current_user.expenses.search(params[:search])
	end

	# (for later use)
	# def mdate
 	#   month = params[:month_select]
 	#   redirect_to :action => "index"
	# end

	def new
		@expense = Expense.new

		@categories = Category.where('active = true').sort{|x,y| counts(y.id) <=> counts(x.id)}

		if params[:category] && params[:search]
			@expenses = current_user.expenses(conditions: ['description LIKE ?', "%#{params[:search]}%"])
			@expenses.select!{ |c| c.category_id == params[:category] }
		elsif params[:category]
			@expenses = current_user.expenses.where(category_id: params[:category])
		elsif params[:search]
			@expenses = Expense.all(conditions: ['description LIKE ?', "%#{params[:search]}%"])
		else
			@expenses = current_user.expenses
		end
	end

	def new_income
		@expense = Expense.new

		@categories = Category.where('active = true').sort{|x,y| counts(y.id) <=> counts(x.id)}

		if params[:category] && params[:search]
			@expenses = current_user.expenses(conditions: ['description LIKE ?', "%#{params[:search]}%"])
			@expenses.select!{ |c| c.category_id == params[:category] }
		elsif params[:category]
			@expenses = current_user.expenses.where(category_id: params[:category])
		elsif params[:search]
			@expenses = Expense.all(conditions: ['description LIKE ?', "%#{params[:search]}%"])
		else
			@expenses = current_user.expenses
		end
	end

	def create
		@expense = current_user.expenses.build(expense_params)
		@expense.save
		if @expense.save
			redirect_to expenses_path
		else
			@categories = Category.where('active = true').sort{|x,y| counts(y.id) <=> counts(x.id)}
			render 'new'
		end
	end

	def destroy
		@expense = current_user.expenses.find(params[:id])
		@expense.destroy
   	redirect_to expenses_path
	end

	def edit

		@expense = Expense.find(params[:id])

		@categories = Category.where('active = true').sort{|x,y| counts(y.id) <=> counts(x.id)}

		if params[:category] && params[:search]
			@expenses = current_user.expenses(conditions: ['description LIKE ?', "%#{params[:search]}%"])
			@expenses.select!{ |c| c.category_id == params[:category] }
		elsif params[:category]
			@expenses = current_user.expenses.where(category_id: params[:category])
		elsif params[:search]
			@expenses = Expense.all(conditions: ['description LIKE ?', "%#{params[:search]}%"])
		else
			@expenses = current_user.expenses
		end
	end

	def update
		@expense = current_user.expenses.find(params[:id])
		@expense.update(expense_params)
		redirect_to expenses_path
	end

	def show
		@expense = current_user.expenses.find(params[:id])

		@categories = Category.where('active = true').sort{|x,y| counts(y.id) <=> counts(x.id)}

		if params[:category] && params[:search]
			@expenses = current_user.expenses(conditions: ['description LIKE ?', "%#{params[:search]}%"])
			@expenses.select!{ |c| c.category_id == params[:category] }
		elsif params[:category]
			@expenses = current_user.expenses.where(category_id: params[:category])
		elsif params[:search]
			@expenses = Expense.all(conditions: ['description LIKE ?', "%#{params[:search]}%"])
		else
			@expenses = current_user.expenses
		end

		@date1 = @expense.date
		@date2 = @date1.strftime("%d. %B, %Y")
	end

	def statistics
		@categories = Category.all.where(active: true).sort{|x,y| count_exps_month(y.id) <=> count_exps_month(x.id)}
		@week_list = Category.all.where(active: true).sort{|x,y| count_exps_week(y.id) <=> count_exps_week(x.id)}

		@expenses = current_user.expenses	
		@date1 = Date.today 
		@date2 = @date1.strftime("%B")
		@total = @expenses.where("date > ?", Date.today.at_beginning_of_month).sum(:expense_value)
		@avg_exp = (@expenses.where("date > ?", Date.today.at_beginning_of_month).sum(:expense_value)/30).round(2)
		@avg_exp_week = (@expenses.where("date > ?", (Date.today-6.days)).sum(:expense_value)/7).round(2)
		@max = @expenses.where("date > ?", Date.today.at_beginning_of_month).maximum(:expense_value)

		@income = @expenses.where("date > ? and outcome = false", Date.today.at_beginning_of_month).sum(:expense_value)
		@outcome = @expenses.where("date > ? and outcome = true", Date.today.at_beginning_of_month).sum(:expense_value)
		@saldo = @income - (@outcome).abs

		gon.income = @expenses.where("date > ? and outcome = false", Date.today.at_beginning_of_month).sum(:expense_value)
		gon.outcome = @expenses.where("date > ? and outcome = true", Date.today.at_beginning_of_month).sum(:expense_value)

		@budget_items = current_user.budget_items.where(budget_date: Date.today.at_beginning_of_month)
		@budget = @budget_items.sum(:value)

		@money_left = @budget - (@saldo).abs

		@income_today = @expenses.where("date = ? and outcome = false", Date.today).sum(:expense_value)
		@outcome_today = @expenses.where("date = ? and outcome = true", Date.today).sum(:expense_value)

		@total_today = @income_today - (@outcome_today).abs

		@rec_today = -(@budget/((Date.today + 1.month).at_beginning_of_month - 1.days).day).abs
	end

	def count_exps_month(category_id)
		@expenses2 = current_user.expenses.where("date > ?", Date.today.at_beginning_of_month)
		@categories3 = Category.all.where(active: true)
		@categories3.each do |sum_of_exps|
			@sum_of_exps = @expenses2.where(category_id: category_id).sum(:expense_value)
		end
		return @sum_of_exps
	end

	def count_exps_week(category_id)
		@expenses2 = current_user.expenses.where("date > ?", (Date.today-6.days))
		@categories4 = Category.all.where(active: true)
		@categories4.each do |sum_of_exps|
			@sum_of_exps = @expenses2.where(category_id: category_id).sum(:expense_value)
		end
		return @sum_of_exps
	end

	private
	
	def expense_params
		params.require(:expense).permit(:description, :date, :outcome, :expense_value, :location_id, :category_id, :bill)
	end
end

app/helpers/expenses_helper.rb
 module ExpensesHelper
  def expenses_chart_data
  	expenses_by_day = current_user.expenses.where(outcome: true).total_grouped_by_day(Date.today - 1.month )
		((Date.today - 1.month)..Date.today).map do |d|
			{
				date: d.to_date,
				expense_value: expenses_by_day.fetch(d, []).first.try(:total_expense) || 0
			}
		end
  end

  def expenses_chart_data2
  	expenses_by_day = current_user.expenses.where(outcome: true).total_grouped_by_day(Date.today.at_beginning_of_month)
		(Date.today.at_beginning_of_month..Date.today).map do |d|
			{
				date: d.to_date,
				expense_value: expenses_by_day.fetch(d, []).first.try(:total_expense) || 0
			}
		end
  end

  def expenses_chart_data_week
  	expenses_by_day = current_user.expenses.where(outcome: true).total_grouped_by_day((Date.today-6.days))
	((Date.today-6.days)..Date.today).map do |d|
		{
			date: d.to_date,
			expense_value: expenses_by_day.fetch(d, []).first.try(:total_expense) || 0
		}
	end
  end

  def expenses_by_category_chart
  	Category.where(active: true).map do |n|
  		{
  			name: n.name,
  			expense_value: current_user.expenses.where('category_id = ? and date > ?', n.id, Date.today.at_beginning_of_month).sum(:expense_value).to_s
  		}
  	end
  end

 #  def category_expenses
 #  	expenses_by_category = Expense.total_expense_by_month(Date.today.at_beginning_of_month)
	# name: cat_names
	# expense_value = expenses_by_category
 #  end
end

app/views/expenses/_categories_list.html.erb
<div class="col-md-3">
  <div class="list-group">
    <a href="/expenses" class="list-group-item active">
      All Expenses
    </a>
    <% @categories.each do |c| %>
      <% if current_page? expenses_path(category: c.id, page: params[:page]) || %>
        <%= link_to expenses_path(category: c.id), class: "list-group-item active1" do %>
          <%= c.name %> <span class="badge"><%= counts(c.id) %></span>
        <% end %>
      <% else %>
        <%= link_to expenses_path(category: c.id), class: "list-group-item" do %>
          <%= c.name %> <span class="badge"><%= counts(c.id) %></span>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/expenses/_categories_list_index.html.erb
<div class="col-md-3">
  <div class="list-group">
    <center> 
        <span style="font-size: 11px", class="label label-success">Income: <%= number_with_precision(@income, :precision => 2, :delimiter => ',') %> € 
        </span>&nbsp;
        <span style="font-size: 11px", class="label label-danger">Outcome: <%= number_with_precision(-(@outcome).abs, :precision => 2, :delimiter => ',') %> € 
        </span>
      <br/>
      <br/>
    </center>
    <a href="/expenses" class="list-group-item active">
      All Expenses
    </a>
    <% @categories.each do |c| %>
      <% if current_page? expenses_path(category: c.id, page: params[:page]) || %>
        <%= link_to expenses_path(category: c.id), class: "list-group-item active1" do %>
          <%= c.name %> <span class="badge"><%= counts(c.id) %></span>
        <% end %>
      <% else %>
        <%= link_to expenses_path(category: c.id), class: "list-group-item" do %>
          <%= c.name %> <span class="badge"><%= counts(c.id) %></span>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/expenses/_details.html.erb
<ul class="nav nav-tabs">
	<li class="active"> <%= link_to "Show", expense_path(@expense) %></li>
	<li ><%= link_to "Edit", edit_expense_path(@expense) %></li>
	<li><%= link_to "Delete", expense_path(@expense), method: "delete", data: {confirm: 'Are you sure?'} %></li>
	<div class="panel panel-default">
		<div align="right" class="panel-heading">Expense Manager</div>
			<div class="panel-body">
				<div class="well" align="center" style="font-size:35px"><span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;<%= @expense.category.name %></div>
				<div class="panel panel-default">
					<div class="panel-body">
						<div align="center" style="font-size:35px"><strong><%= @expense.expense_value %> €</strong></div>
						<br/>
						<div class="thumbnail">
						<center><%= image_tag @expense.bill.url(:medium) %></div><br/><br/></center>
						<div style="font-size:15px" class="note"><strong>You've spent <%= @expense.expense_value %>€ when you <%= @expense.description.downcase %>.</strong>
						</div>
					</div>
				</div>
				<div align="right" style="font-size:13px"><%= @date2 %><br/>
				<% if @expense.location %>
          <% if @expense.location.name == "Abroad" %>
            <br/><span style="font-size:12px;"><%= @expense.location.name %></span>
          <% else %>
            <br/><span style="font-size:12px;">In: <%= @expense.location.name %></span>
          <% end %>
        <% end %></div>
			</div>
		</div>
	</div>
</ul>

app/views/expenses/_expenses_list.html.erb
<div class="container">
    <div class="row">
    <%= render 'categories_list_index' %>
      <div class="col-md-9">
        <center>
          <span style="font-size: 11px", class="label label-primary">Budget: <%= number_with_precision(@budget, :precision => 2, :delimiter => ',') %></span> <span style="font-size: 11px", class="label label-primary">Expenses: <%= number_with_precision(@total, :precision => 2, :delimiter => ',') %></span> 
          <% if @money_left > 0 %>
            <span style="font-size: 11px", class="label label-warning">Money left: <%= number_with_precision(@money_left, :precision => 2, :delimiter => ',') %></span>
          <% else %>
            <span style="font-size: 11px", class="label label-danger">Deficit: <%= number_with_precision(@money_left, :precision => 2, :delimiter => ',') %></span>
          <% end %>
          <div class="row"><%= content_tag :div, "", id: "expenses-chart", data: {expenses: expenses_chart_data} %>
        </div>
        <% if @budget >= @total.abs %>
          <div class="progress progress-striped active">
            <div class="progress-bar"  role="progressbar" aria-valuenow="<%= @percentage%>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @percentage%>%">
              <span class="sr-only"><%= @percentage%>% Complete</span>
            </div>
          </div>
        <% else %>
          <div class="progress">
            <div class="progress-bar progress-bar-danger" style="width: 100%">
              <span class="sr-only">100% Complete (danger)</span>
            </div>
          </div>
        <% end %>
        </center>
        <% @expenses.each_with_index do |expense, index| %>
          <% if index % 4 == 0 %>
            <div class="row">
          <% end %>
            <div class="col-md-3">
              <div class="thumbnail">
                <div class="caption">
                <% if expense.category.name == "Family & Personal" %>
                  <h3 class="ex_c">Personal</h3>
                <% else %>
                  <h3 class="ex_c"><%= expense.category.name %></h3>
                <% end %>
                  <%= expense.date.strftime("%d. %B,  %Y.") %>
                  <% if expense.location %>
                    <% if expense.location.name == "Abroad" %>
                      <br/><span style="font-size:12px;"><%= expense.location.name %></span>
                    <% else %>
                      <br/><span style="font-size:12px;">In: <%= expense.location.name %></span>
                    <% end %>
                  <% end %>
                </div>
                <%= image_tag expense.bill.url(:medium), size: '170x105' %>
                <div class="caption">
                  <p><center><h4 class="ex_v">
                  <% if expense.outcome == true %>
                  <span style="color:red" class="glyphicon glyphicon-download"></span>&nbsp;&nbsp;<%= -expense.expense_value.abs %>€ 
                  <% else %>
                  <span style="color:green" class="glyphicon glyphicon-upload"></span>&nbsp;&nbsp;<%= expense.expense_value %>€ 
                  <% end %>
                  </h4></center></p>
                  <p align="center">
                    <%= link_to expense_path(expense), class: "btn btn-primary", role: "button" do %>
                        <span style="font-size:10px;">Show</span>
                     <% end %>
                    <%= link_to edit_expense_path(expense), class: "btn btn-default", role: "button" do %>
                      <span style="font-size:10px;">Edit</span>
                    <% end %>
                    <%= link_to expense_path(expense), class: "btn btn-default", method: :delete, data: {confirm: 'Are you sure?', role: "button"} do %>
                      <span style="font-size:10px;">Delete</span>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          <% if index % 4 == 3 %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/expenses/_form.html.erb
<%= form_for @expense, {role: "form"} do |f| %>
  <div class="form-group">
    <%= f.hidden_field :outcome, value: true %>
    <%= f.label :description, "Description" %>
    <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
    <%= f.label :expense_value, "Amount" %>
    <%= f.text_field :expense_value, class: "form-control", placeholder: "How much?"  %>
    <div class="date" data-behaviour="datepicker">
      <%= f.label :date, "Date" %>
      <%= f.text_field :date, value: Date.today, class: "form-control"%><p class="input-group-addon"></p>
    </div>
    <%= f.label :category_id, "Category" %>
    <%= f.collection_select(:category_id, Category.active_outcome, :id, :name,  {prompt: "Select a category"}, {class: "form-control"}) %>
    
    <%= f.label :location_id, "Location" %><br/>
    <%= f.hidden_field :location_id, {class: "form-control"} %><br/>

    <%= f.label :bill_id, "Upload photo" %><br/>
    <%= f.file_field :bill, {class: "form-control"}%>
  </div>
  <center><button type="submit" class="btn btn-primary">Add expense</button></center>
<% end %><br/>

app/views/expenses/_income_form.html.erb
<%= form_for @expense, {role: "form"} do |f| %>
  <br/>   
  <div class="form-group">
    <%= f.hidden_field :outcome, value: false %>
    <%= f.label :description, "Description" %>
    <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
    <%= f.label :expense_value, "Amount" %>
    <%= f.text_field :expense_value, class: "form-control", placeholder: "How much?"  %>
    <div class="date" data-behaviour="datepicker">
      <%= f.label :date, "Date" %>
      <%= f.text_field :date, value: Date.today, class: "form-control"%><p class="input-group-addon"></p>
    </div>
    <%= f.label :category_id, "Category" %>
    <%= f.collection_select(:category_id, Category.active_income, :id, :name,  {prompt: "Select a category"}, {class: "form-control"}) %>
    <%= f.label :location, "Location" %>
    <%= f.collection_select(:location_id, Location.all, :id, :name, {prompt: "Select a location", selected: 17}, {class: "form-control"}) %>
    <%= f.label :bill_id, "Upload photo" %><br/>
    <%= f.file_field :bill, {class: "form-control"}%>
  </div>
  <center><button type="submit" class="btn btn-primary">Add expense</button></center>
<% end %><br/>

app/views/expenses/_update_form.html.erb
<ul class="nav nav-tabs">
  <li> <%= link_to "Show", expense_path(@expense) %></li>
  <li class="active"><%= link_to "Edit", edit_expense_path(@expense) %></li>
  <li><%= link_to "Delete", expense_path(@expense), method: "delete", data: {confirm: 'Are you sure?'} %></li>
  <div class="panel panel-default">
    <div align="right" class="panel-heading">Expense Manager</div>
      <div class="panel-body">
        <%= form_for @expense, {role: "form"} do |f| %> 
        <legend>Edit expense</legend>     
        <div class="form-group">
          <%= f.label :description, "Description" %>
          <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
          <%= f.label :expense_value, "Amount" %>
          <%= f.text_field :expense_value, class: "form-control", placeholder: "How much?"  %>
          <div class="date" data-behaviour="datepicker">
          <%= f.label :date, "Date" %>
          <%= f.text_field :date, value: Date.today, class: "form-control" %><p class="input-group-addon"></p>
          </div>
          <%= f.label :location, "Location" %>
          <%= f.collection_select(:location_id, Location.all, :id, :name, {}, {class: "form-control"}) %>
          <% if @expense.category.outcome == true %>
            <%= f.label :category_id, "Category" %>
            <%= f.collection_select(:category_id, Category.where(active: true, outcome: true), :id, :name,  {prompt: "Select a category"}, {class: "form-control"}) %>
          <% elsif @expense.category.outcome == false %>
            <%= f.label :category_id, "Category" %>
            <%= f.collection_select(:category_id, Category.where(active: true, outcome: false), :id, :name,  {prompt: "Select a category"}, {class: "form-control"}) %>
          <% end %>
          <%= f.label :bill_id, "Upload photo" %><br/>
          <%= f.file_field :bill, {class: "form-control"}%>
        </div>
        <button type="submit" method="patch" class="btn btn-primary">Save changes</button>
        <% end %>
      </div>
    </div>
  </div>
</ul>

app/views/expenses/index.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Expense manager</title>
	</head>
	<body>
		<%= render 'expenses_list' %>
	</body>
</html>

app/views/expenses/new.html.erb
<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Expense manager</title>
	</head>
	<body>
	<div class="container">
		<div class="row">
			<%= render 'categories_list' %>
		<div class="col-md-2">
		</div>
		<div class="col-md-5">
	    	<div class="row">
	    	<%= render 'expenses/shared/error' %>
	    	<br/>
	            <div class="thumbnail">
	            	<ul class="nav nav-tabs">
						<li class="active"> 
							<%= link_to "Outcome" %>
						</li>
						<li><%= link_to "Income", expenses_new_income_path %></li>
						<div class="panel panel-default">
							<div align="right" class="panel-heading">Expense Manager</div>
							<div class="panel-body">
							    <%= render :partial => 'form'  %>
							</div>
						</div>
					</ul>
				</div>
			</div>
		</div>
		<div class="col-md-2">
		</div>
		</div>
	</div>
	</body>
</html>

app/views/expenses/statistics.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Expense manager</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading"><strong>Statistics</strong></div>
              <div class="panel-body">
              <center>
                <%= content_tag :div, "", id: "expenses-chart2", data: {expenses: expenses_chart_data2} %>
                <br/>
                <span class="label label-info" style="font-size: 12px">Month</span>&nbsp;&nbsp; <strong>
                  <%= @date2 %>
                </strong>&nbsp;&nbsp;&nbsp; 
                <span class="label label-info" style="font-size: 12px">Total expenses</span>&nbsp;&nbsp;  
                <strong>
                  <%= number_with_precision(@total, :precision => 2, :delimiter => ',') %> €
                </strong>&nbsp;&nbsp;&nbsp; 
                <span class="label label-info" style="font-size: 12px">
                  Max. expense
                </span>&nbsp;&nbsp;   
                <strong>
                  <%= number_with_precision(@max, :precision => 2, :delimiter => ',') %> €
                </strong>
                <br/>
              </center>
              <br/>
                <div class="panel panel-primary">
                  <div class="panel-heading"><strong>Budget</strong></div>
                    <table class="table" align="center">
                    <tr>
                      <td>
                        <strong>Budget</strong>
                      </td>
                      <td>
                        <%= number_with_precision(@budget, :precision => 2, :delimiter => ',') %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <strong>Incomes & Outcomes</strong>
                      </td>
                      <td>
                        <%= number_with_precision(@saldo, :precision => 2, :delimiter => ',') %>
                      </td>
                    </tr>
                    <tr><td><center><%= content_tag :div, "", id: "income_chart" %><br/></center></td></tr>
                    <tr>
                      <td>
                        Today's income
                      </td>
                      <td>
                        <%= number_with_precision(@income_today, :precision => 2, :delimiter => ',') %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        Today's outcome
                      </td>
                      <td>
                        <%= number_with_precision(@outcome_today, :precision => 2, :delimiter => ',') %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <strong>Today's total</strong>
                      </td>
                      <td>
                        <strong><%= number_with_precision(@total_today, :precision => 2, :delimiter => ',') %></strong>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        Budget daily expenses
                      </td>
                      <td>
                        <%= number_with_precision(@rec_today, :precision => 2, :delimiter => ',') %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <strong>Wallet</strong>
                      </td>
                      <td>
                        <strong><%= number_with_precision(@money_left, :precision => 2, :delimiter => ',') %></strong>
                      </td>
                    </tr>
                    </table>
                    <%= javascript_tag do %>
                      window.expensesURL = "<%= expenses_url %>";
                      window.expenses = <%=raw @income.to_json %>
                    <% end %>

                </div>
                <div class="panel panel-danger">
                  <div class="panel-heading">Your top 3 EM categories</div>
                  <div class="panel-body">
                    <p>In this month, you've spent most of your money on:</p>
                  </div>
                  <table class="table" align="center">
                    <% @categories[0..2].each do |c| %>
                    <tr>
                      <td>
                        <%= c.name %>
                      </td> 
                      <td>
                        <strong><%= number_with_precision(count_exps(c.id), :precision => 2, :delimiter => ',') %> €</strong>
                      </td>
                    </tr>
                    <% end %>
                  </table>
                  <center><%= content_tag :div, "", id: "categs_chart", data: {eexpenses: expenses_by_category_chart} %><br/>
                <span class="label label-info" style="font-size: 12px">Average daily expense</span>&nbsp;&nbsp; <strong>
                  <%= number_with_precision(@avg_exp, :precision => 2, :delimiter => ',') %> €
                </strong>&nbsp;&nbsp;&nbsp;</center><br/>
                </div>
                <div class="panel panel-success">
                <div class="panel-heading">Last 7 days</div>
                <div class="panel-body">
                <p>In this seven days, you've spent most of your money on:</p>
                <table class="table" align="center">
                  <% @week_list[0..2].each do |c| %>
                  <tr>
                    <td>
                      <%= c.name %>
                    </td> 
                    <td>
                      <strong><%= number_with_precision(count_exps_week(c.id), :precision => 2, :delimiter => ',') %> €</strong>
                    </td>
                  </tr>
                  <% end %>
                </table>
                <center><%= content_tag :div, "", id: "expenses-chart-week", data: {expensesw: expenses_chart_data_week} %><br/>
                <span class="label label-info" style="font-size: 12px">Average daily expense</span>&nbsp;&nbsp; <strong>
                  <%= number_with_precision(@avg_exp_week, :precision => 2, :delimiter => ',') %> €
                </strong>&nbsp;&nbsp;&nbsp;</center><br/>
                </div>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>