config/routes.rb
Expman::Application.routes.draw do
  devise_for :users

  get 'expenses/statistics'
  get 'expenses/new_income'
  resources :expenses

  get 'categories/customize'
  resources :categories do
      put :score, on: :collection
  end

  resources :locations

  match 'budget_items/create_budget', via: :post
  match 'budget_items/edit_budget', via: :get
  match 'budget_items/update_budget', via: :put
  match 'budget_items/delete_budget', via: :delete
  resources :budget_items
  
  #match 'locations', to: 'locations#index', via: :get

  root to: 'high_voltage/pages#show', id: 'homepage'
  #match '/delete', to: 'expenses#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted" align="center"><br/>Copyright © 2014 Ideus</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="/"><img src="<%= image_path('em.png') %>"  height="24px" width="24px" /> Expense Manager</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">
			<% if user_signed_in? %>
				<li class="active"><a href="/expenses">My expenses</a></li>
				<li><a href="/expenses/new/">New expense</a></li>
			<% end %>
		</ul>
		<% if user_signed_in? %>
			<%= form_tag expenses_path, method: 'get', class: "navbar-form navbar-left", role: "search" do  %>
			<div class="form-group">
				<%= text_field_tag :search, params[:search], { class: "form-control", placeholder: "Find your expense", id: "Search" } %>
			</div>
				<%= submit_tag "Search", { class: "btn btn-default", name: nil }%>
			<% end %>	
		<% end %>	
		<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
				<li><a href="/expenses/statistics">Statistics</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Download<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to "CSV", expenses_path(format: "csv") %></li>
						<li><%= link_to "XLS", expenses_path(format: "xls") %></li>
					</ul>
				</li>
			<% end %>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
				<ul class="dropdown-menu">
					<% if user_signed_in? %>
						<li><a href="/budget_items/">Budget</a></li>
						<li><a href="/categories/customize">Categories</a></li>
						<li><a href="/users/edit">Profile</a></li>
						<li><a data-method="delete" href="/users/sign_out">Sign out</a></li>
					<% end %>
					<% if !user_signed_in? %>
						<li><a href="/users/sign_in/">Sign in</a></li>
						<li><a href="/users/sign_up/">Register</a></li>
					<% end %>
				</ul>
			</li>
		</ul>
	</div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expense manager</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<div id="holder">
<body>
	<%= render 'layouts/header' %>
	<% if notice %>
	  <p class="alert alert-notice"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-error"><%= alert %></p>
	<% end %>

	<%= yield %>
</body>

<%= render 'layouts/footer' %>

</div>
</html>